local M = {}

M.TABLE_SYMBOLS = {
    -- light
    { style = 'light', name = 'horizontal', symbol = '─' },
    { style = 'light', name = 'vertical', symbol = '│' },
    { style = 'light', name = 'down and right', symbol = '┌' },
    { style = 'light', name = 'down and left', symbol = '┐' },
    { style = 'light', name = 'up and right', symbol = '└' },
    { style = 'light', name = 'up and left', symbol = '┘' },
    { style = 'light', name = 'vertical and right', symbol = '├' },
    { style = 'light', name = 'vertical and left', symbol = '┤' },
    { style = 'light', name = 'down and horizontal', symbol = '┬' },
    { style = 'light', name = 'up and horizontal', symbol = '┴' },
    { style = 'light', name = 'vertical and horizontal', symbol = '┼' },
    { style = 'light', name = 'left', symbol = '╴' },
    { style = 'light', name = 'up', symbol = '╵' },
    { style = 'light', name = 'right', symbol = '╶' },
    { style = 'light', name = 'down', symbol = '╷' },
    -- heavy
    { style = 'heavy', name = 'horizontal', symbol = '━' },
    { style = 'heavy', name = 'vertical', symbol = '┃' },
    { style = 'heavy', name = 'down and right', symbol = '┏' },
    { style = 'heavy', name = 'down and left', symbol = '┓' },
    { style = 'heavy', name = 'up and right', symbol = '┗' },
    { style = 'heavy', name = 'up and left', symbol = '┛' },
    { style = 'heavy', name = 'vertical and right', symbol = '┣' },
    { style = 'heavy', name = 'vertical and left', symbol = '┫' },
    { style = 'heavy', name = 'down and horizontal', symbol = '┳' },
    { style = 'heavy', name = 'up and horizontal', symbol = '┻' },
    { style = 'heavy', name = 'vertical and horizontal', symbol = '╋' },
    { style = 'heavy', name = 'left', symbol = '╸' },
    { style = 'heavy', name = 'up', symbol = '╹' },
    { style = 'heavy', name = 'right', symbol = '╺' },
    { style = 'heavy', name = 'down', symbol = '╻' },
    -- double
    { style = 'double', name = 'horizontal', symbol = '═' },
    { style = 'double', name = 'vertical', symbol = '║' },
    { style = 'double', name = 'down single right', symbol = '╒' },
    { style = 'double', name = 'down right single', symbol = '╓' },
    { style = 'double', name = 'down right', symbol = '╔' },
    { style = 'double', name = 'down single left', symbol = '╕' },
    { style = 'double', name = 'down left single', symbol = '╖' },
    { style = 'double', name = 'down left', symbol = '╗' },
    { style = 'double', name = 'up single right', symbol = '╘' },
    { style = 'double', name = 'up right single', symbol = '╙' },
    { style = 'double', name = 'up right', symbol = '╚' },
    { style = 'double', name = 'up single left', symbol = '╛' },
    { style = 'double', name = 'up left single', symbol = '╜' },
    { style = 'double', name = 'up left', symbol = '╝' },
    { style = 'double', name = 'vertical single right', symbol = '╞' },
    { style = 'double', name = 'vertical right single', symbol = '╟' },
    { style = 'double', name = 'vertical right', symbol = '╠' },
    { style = 'double', name = 'vertical single left', symbol = '╡' },
    { style = 'double', name = 'vertical left single', symbol = '╢' },
    { style = 'double', name = 'vertical left', symbol = '╣' },
    { style = 'double', name = 'down single horizontal ', symbol = '╤' },
    { style = 'double', name = 'down horizontal single', symbol = '╥' },
    { style = 'double', name = 'down horizontal', symbol = '╦' },
    { style = 'double', name = 'up single horizontal', symbol = '╧' },
    { style = 'double', name = 'up horizontal single', symbol = '╨' },
    { style = 'double', name = 'up horizontal', symbol = '╩' },
    { style = 'double', name = 'vertical single horizontal', symbol = '╪' },
    { style = 'double', name = 'vertical horizontal single', symbol = '╫' },
    { style = 'double', name = 'vertical horizontal', symbol = '╬' },
    -- arc
    { style = 'arc', name = 'down and right', symbol = '╭' },
    { style = 'arc', name = 'down and left', symbol = '╮' },
    { style = 'arc', name = 'up and left', symbol = '╯' },
    { style = 'arc', name = 'up and right', symbol = '╰' },
}

return M
